import type { Metadata } from "next";
import { Google_Sans, Google_Sans_Code } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { AppHeader } from "@/components/app-header";

const googleSans = Google_Sans({
  variable: "--font-google-sans",
  subsets: ["latin"],
});

const googleSansCode = Google_Sans_Code({
  variable: "--font-google-sans-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id" className="scroll-smooth overflow-y-auto">
      <body
        className={cn(
          googleSans.variable,
          googleSansCode.variable,
          "font-sans antialiased flex flex-col bg-background text-foreground overflow-x-hidden",
        )}
      >
        <AppHeader />
        <main className="size-full bg-transparent min-w-xs mx-auto max-w-7xl">
          {children}
        </main>
      </body>
    </html>
  );
}
